name: Deploy to production via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./WebRoot/
          server-dir: /www/
          state-name: ftp-deploy-sync-state.json
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            _attatch/**
            .well-known/**